/* Eindhoven Nights — places data
   tier = price bucket for sorting (1=cheapest ... 5). 'free-ish' uses 1.
   img = Google place photo (loads live in browser). maps link built from placeId. */
window.DATA = {
  restaurants: [
    { name:"Takumi Ramen", area:"Nieuwstraat · Centrum", tier:1, cost:"€15–25 pp", vibe:"Ramen",
      desc:"The best ramen in town — rich, authentic tonkotsu broth and a cosy buzz. Expect a short queue; no reservations, just go and slurp.",
      placeId:"ChIJjcN1hG3ZxkcR54oXm6RmpuQ", q:"Takumi Ramen Eindhoven Nieuwstraat",
      web:"https://www.takumiramennoodles.com/nl/eindhoven-nieuwstraat/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMrDlXoLOEvoUQB2J6cttJTHk9UAGTg317IQJ4L0LzXto099RUYFaw7vkaMPCCWZ7b7NX1je9tivVwknFgFLkCfBHXu_ndAdhfXGvTn4tT8_ZnSiADUFZbwjXHif5ELAztFcPL2G4Ee-S7JKTcF5Qb10Q=s1600-w1000" },

    { name:"Wasven Gasterij", area:"Tongelre", tier:1, cost:"€10–18 lunch", vibe:"Farm-to-table",
      desc:"A working bio-farm with its own veg garden and bakery, tucked between woods. Most of the plate is grown on-site. Walk it off in the forest after.",
      placeId:"ChIJu4vXyb_YxkcRBa9_GYw0GPs", q:"Wasven Gasterij Eindhoven",
      web:"http://www.wasven.nl/", insta:"https://www.instagram.com/wasven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNpHwKcn_ed4b-VGJa-iJq6YuGrUYvlD7couVbL89XFbxBD8aCkSzQuXx-6W__h5_1YGMzShE9dN-iyqpETNT9NDbgQMiQfUAGTLwM2wUE3oZDZ8dcXnb042-Rf_WwIPybbkfgH5XzF77-_CaIhv-Cdyw=s1600-w1000" },

    { name:"Down Town Gourmet Market", area:"Smalle Haven · Centrum", tier:2, cost:"€15–25 pp", vibe:"Food hall",
      desc:"A buzzing SE-Asian-street-market-style food hall — many kitchens under one roof, plus an all-you-can-eat option. Loud, lively, perfect for a group with mixed cravings.",
      placeId:"ChIJtfSa9wLZxkcR_PsNpWW8r48", q:"Down Town Gourmet Market Eindhoven",
      web:"https://downtowngourmetmarket.com/", insta:"https://www.instagram.com/downtowngourmetmarket/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOYKuiOIX35Vy8msM_qbchkxLzDAItwRYOfkdG2dJ1u2owV3EcbpDgoaNUTtIhUSbubKwoGpw78_jm5cR7GXsfKFL4KrSB-nev4xflQFBTaS33n3RJHwaiWpY-fP_4euaQPtW6kCaPWC7g37Q=s1600-w1000" },

    { name:"Hout", area:"Strijp-S", tier:2, cost:"€15–25 pp", vibe:"Pizza",
      desc:"Neapolitan pizzeria in a big, high-ceilinged room. Outstanding dough, proper tiramisu, fast service. Works for a date or a crowd.",
      placeId:"ChIJo4RDOADZxkcRKR6Y-osYKrA", q:"Hout Eindhoven",
      web:"https://www.houteindhoven.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZPCnh74lR8tP9nWeVaFhFuNbaE1QiCnmOwBCRFcNdMo0x_r8KiHF48G3zP1uBYcX4Ky39BQhY8TC8LDcITt97R1HPB_qrw6_dmMV2d0H-8fN_whhlg9ANDYPkMJMSNPVqdT74mraJz549dn981v0uJxSg=s1600-w1000" },

    { name:"Pummaró", area:"Sint-Trudoplein", tier:2, cost:"€15–25 pp", vibe:"Pizza",
      desc:"Cosy neighbourhood pizzeria with a little garden and a warm Italian welcome. Soft, well-made pizza and a family vibe.",
      placeId:"ChIJU52dThHZxkcRWFYxe35wnE4", q:"Pummaro Eindhoven",
      web:"http://www.pummaro.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNo2gJC9BoyCPrx159Q_1PcMfrrEh7Z5pe1M3EP-s-ykB3yIwTbRYcHYYiYEAsz0ZaZduwJYpYT_cZE3MYp_9bnl34qgEqNBBuwOPOixuS1y__puHDAmQ2Q-QsCSFBY7IA7DcIFVfL02mvDSQ=s1600-w1000" },

    { name:"superMARKT restobar", area:"Woenselse Markt", tier:2, cost:"€15–25 pp", vibe:"Hidden gem",
      desc:"A little gem in a chaotic neighbourhood. Small simple menu, fresh ingredients, a self-imported list of small French wines and a great sound system.",
      placeId:"ChIJU7wFBSHZxkcRysOMeNvJHK4", q:"superMARKT restobar Eindhoven",
      web:"https://supermarkteindhoven.nl/", insta:"https://www.instagram.com/supermarkt.eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMq2Ff4I7JXv71_cWOu2WORW96qPfvx4l0jHkZrhrFnlOv6YerVg9rTUkHpzdfN4oJFdpx49394xhbNnF8Rzipy4sauMDMlQLdhN7o-0uExqujXQ7jtqhiu09rwf5FTAkHwhbj0EOwxDDFRPiH25X72=s1600-w1000" },

    { name:"Otomoto", area:"Vrijstraat · Centrum", tier:2, cost:"€20–35 pp", vibe:"Listening bar",
      desc:"A Japanese-inspired listening bar: natural wines, dumplings and small plates, vinyl all night. Menu changes with guest chefs. No bookings — one of the chillest rooms in town.",
      placeId:"ChIJ8azhtzzZxkcR9kL-VXcaqVM", q:"Otomoto Eindhoven",
      web:"https://www.otomotosocial.com/", insta:"https://www.instagram.com/otomoto.social/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOyN3gEbSSEXl6VEhDxs_rTONlNxhwGYrTefENeFsxKCnvs6UW_SXzbqSrb5697W_suRAh8CmB5GvihrH1h-urAhLAwF45W_NyiYSEEwm9wsUy3tucRiEcQ8LwJAuPfIv-Buw7r_kfgGgNS8A=s1600-w1000" },

    { name:"Tres Tapasbar", area:"Emmasingel · Centrum", tier:2, cost:"€20–35 pp", vibe:"Tapas",
      desc:"Spanish tapas in the centre, made for sharing and good for groups. Lively, diverse menu with veggie options.",
      placeId:"ChIJc6ovwJHZxkcRoiO-Oza7Lpc", q:"Tres Tapasbar Eindhoven",
      web:"https://www.trestapasbar.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNOUU9zQOZdUQ2vlaEF8MO668A8AT0-5h43d7VkbZ-_VvHcBpdY1ghQ6LgP_LmEmtc1Ym5E0ezlESYtmtgb8VfV368E42cdOWPNFNeFiv5bTUj5TSM5fww4iewxMOHXln8lRmBcBVEJ6GoqDg=s1600-w1000" },

    { name:"La Casera", area:"Keizersgracht · Centrum", tier:2, cost:"€20–35 pp", vibe:"Wine bar",
      desc:"An Italian wine bar (rated 4.9): cured meats, cheeses and every wine by the glass, with warm, expert recommendations. Snug and romantic.",
      placeId:"ChIJ0ZPNZwDZxkcRuowD5c579_E", q:"La Casera Eindhoven",
      web:"https://la-casera.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOhoJdhH8jnUPlR6YJCgwSAkec2qmDmeCFZovL-YjWfV6fI3NrHvDXRe0--AUtDVhIl5KaBgamIGdGeucsYCR8-JynaVNerHRp6QBcMwWOgyj-HBcxygH9OEeehok84WRE_AVPshT7YWiidCA=s1600-w1000" },

    { name:"Le Cozy", area:"Kleine Berg · Centrum", tier:2, cost:"€20–30 pp", vibe:"French bistro",
      desc:"An oldie on lively Kleine Berg. Bistro chairs, classic French menu, oysters and escargots — a corner of Paris for people-watching on the terrace. Romantic and reliable.",
      placeId:"ChIJFZ4P9QTZxkcRne0pMpOvYTc", q:"Le Cozy Eindhoven",
      web:"https://lecozy.nl/", insta:"https://www.instagram.com/lecozy.eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNwzuBfRzqKCZ2dhPbSAVsUyMnHIFCob1_0goaz14TUwM9m46LjIZSIZzt1LiHI3Icsa4ef_5Aeaqiju4jG4D1M2_VZJlPW-_srfcUTcKSmaBmTkmWZRpQ7PIUmjIrMGxjUxr2ycGu_0yCQUQ=s1600-w1000" },

    { name:"Trattoria Mangiare", area:"Kleine Berg · Centrum", tier:2, cost:"€20–30 pp", vibe:"Italian",
      desc:"One of the best Italians in town, warm and welcoming, great for a birthday or a bigger group. Book ahead — it fills up.",
      placeId:"ChIJK-qbRwTZxkcR_Pc4DhvbWQw", q:"Trattoria Mangiare Eindhoven",
      web:"http://www.trattoriamangiare.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNPkzC4Kg5CEUy40O3WBaHIlyiFluwUUD4lxK5zxkSWdloIBXMICXvA-ZKvteGUgFxw3glKkbMepGsP0FrXZVLa-QHdEsf2Y-drplbEKT1WDeHSnHZCGpGsPSIPGPadIzLGRaHLg4iwFtj13A=s1600-w1000" },

    { name:"1910 Restaurant", area:"Willemstraat · Centrum", tier:3, cost:"€25–40 pp", vibe:"Surprise menu",
      desc:"Warm fresh bread, cosy lighting and a much-loved surprise menu that's outstanding value — order as many courses as you dare. Beautiful interior, terrace, strong wines by the glass.",
      placeId:"ChIJAbqIZQXZxkcRuI4W-gIblu8", q:"1910 Restaurant Eindhoven",
      web:"https://1910.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMPIz3wMkPCvR3ySlTp_BwQwl4P02kbG7wmmYfNdztOM9X0KnJgYUGDNYqhy_oqcuBDubMvCzTkY_UsJ6ebtiEQaYHN2mZfL_4W5SKmDdVuqcx02ivkQncnD7orgNgD5kpY6MNG_5h2qpr7=s1600-w1000" },

    { name:"Mrs Park", area:"Meerhoven", tier:3, cost:"€25–40 pp", vibe:"Lakeside",
      desc:"Lakeside spot near the airport with a gorgeous waterfront view. Diverse menu, dog-friendly, open late every day. People wander in off a walk and stay for wine.",
      placeId:"ChIJezjSEQLbxkcRtzOhu3m8zpo", q:"Mrs Park Eindhoven",
      web:"https://mrspark.nl/", insta:"https://www.instagram.com/mrspark.nl/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZME4zzCQCe-1Vu8UNRQZ-X1CrQ46su4LfrV3_pPdoglltRZEjkJX4yvRVUv-ZFIWPkGM8c1GQOVhsdT9_v6u6uetXfGEzdmSuHVeNXlW5LfaCVH4gl8DF-h_tAsFkObAjB217SrlWM3OBMl89Q=s1600-w1000" },

    { name:"Radio Royaal", area:"Strijp-S", tier:3, cost:"€30–40 pp", vibe:"Industrial",
      desc:"Set inside a former Philips power house — raw industrial steel, vintage furniture, foosball. A 3-course menu of refined twists on classics, great price/quality.",
      placeId:"ChIJbZCEA2vZxkcRodV4oBGF6SM", q:"Radio Royaal Eindhoven",
      web:"http://radioroyaal.be/", insta:"https://www.instagram.com/radioroyaal/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOvGB3l1GlsgqED6XmjFUzOpSaBvqbTE0VP9GNctvMnQM9jndTaFv-lxeoy5JNpTnzKVhFepIVEwaVTzFGiK_GGiEkHa-oLTH8L9wGpbx6uU7Iof7gTxJLymldbAwFL1e7uFCsMmTttj3F7tA=s1600-w1000" },

    { name:"Usine", area:"Lichttoren · Centrum", tier:3, cost:"€25–40 pp", vibe:"Industrial",
      desc:"Cavernous industrial-chic space opposite the iconic Lichttoren. Reading corners, exposed concrete and steel, all-day dining with a huge variety of seating. A landmark.",
      placeId:"ChIJVVUVKBvZxkcRGuF6xJVe7g4", q:"Usine Eindhoven",
      web:"https://usine.nl/", insta:"https://www.instagram.com/usine_eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZO3wreg0Ws5o8Ni-uXiXRdsHo-eaLba04sUl8GfUSE6JIXwLl0qsL6gYuO3aXgRmR8IC9FvARe_1tUIrRikKOp8Zr01FQLn1qRcTJxQ_Viiv7r-JQwG3SXE6agUfAGVRoHRC_059Z56dowm=s1600-w1000" },

    { name:"Parkpaviljoen Philips de Jongh", area:"Philips de Jongh Park", tier:3, cost:"€25–40 pp", vibe:"In the park",
      desc:"Literally inside a forested park. Beautifully renovated pavilion with a leafy terrace — eat, then walk or cycle straight into the green. Dog-friendly little slice of paradise.",
      placeId:"ChIJQYAXi1vZxkcRSSCr1N2qdj4", q:"Parkpaviljoen Philips de Jongh Eindhoven",
      web:"http://www.parkpaviljoenpdj.nl/", insta:"https://www.instagram.com/parkpaviljoenpdj/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNlIvlz0AgzoydG0cwjGs_cnWEhRaNuR1yeoRm2Zi3C6EMBC3iLck2wAMr-tMkRH-KI1ccERZ9dSY7QmNIl0t3EenBza_DFn_MT8VExLc5VfnukPeIU9rPAFH-jaX0Jx3ztpjtDNo3eeCXUVs9sX52J-A=s1600-w1000" },

    { name:"De Watermolen van Opwetten", area:"Nuenen (10 min)", tier:3, cost:"€25–40 pp", vibe:"Historic mill",
      desc:"A restored historic water mill on the Kleine Dommel, on the edge of Nuenen and Eindhoven. South-facing terrace over the water and meadows; a footpath leads straight into nature.",
      placeId:"ChIJcSEzn6_YxkcRvdqOVfDAtpI", q:"De Watermolen van Opwetten Nuenen",
      web:"http://www.dewatermolenvanopwetten.nl/", insta:"https://www.instagram.com/dewatermolenvanopwetten/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZO8SAeY1wUSD4No1HeGC_KYoSM8yPZJBKzWxkMXGFdf76rS5rMR-sSe1AZWkDJuLwbnBCLNuCp16A9SBu6x3OWXURtAVyqrd-kBNHHjvsV7JC9PUSV7ybP-N2DyY1_xHwALBBgLbwvUbDWYRw=s1600-w1000" },

    { name:"De Mispelhoef", area:"Oirschotsedijk", tier:3, cost:"€25–40 pp", vibe:"Rustic farm",
      desc:"Heritage farm buildings with a big outdoor terrace and goats on the grounds. Cosy, lively and authentic with a wide menu. A long-time favourite near the airport.",
      placeId:"ChIJbSrqTozbxkcRSIiRKRLiIzU", q:"De Mispelhoef Eindhoven",
      web:"http://www.demispelhoef.nl/", insta:"https://www.instagram.com/demispelhoef/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMNQxGUsJ0E-mPWzWfqoyZDY1Qx5-_lVU-MRTwbhlIapj3Sz0mx5SwkI8PMLMAyNvvUNu6_lifPlqyzoBjJMF3W6IWehZpMe-nbvZ_aWEAFaErUrY8ppw3YMLtzEvEq0rtbt-RLg5H9VXAKMkkGBpOQCQ=s1600-w1000" },

    { name:"Piet Hein Eek", area:"Strijp-R", tier:3, cost:"€20–35 pp", vibe:"Design icon",
      desc:"Restaurant, café, hotel, gallery and shop in the old Philips ceramics factory — the studio of the Netherlands' most famous furniture designer. Rooftop terrace, locally-sourced menus.",
      placeId:"ChIJq0lwKWbZxkcR1-k7fB61YTk", q:"Piet Hein Eek Eindhoven",
      web:"https://www.pietheineek.nl/", insta:"https://www.instagram.com/pietheineek/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZP4v_vrUeoO2RaStQhY8Z37a4wAgE7_VUuek6oPyeLR0KWCGpF31pIhOaDbjVdL10EmrjQB8XRhyt3F18VvUyCnBFi2RyxEqZ7L26sF3eYM1YvbYA_MqABVLUtRVpcJBwQA2kOJpmjvq0ukHw=s1600-w1000" },

    { name:"Stadsbrouwerij Eindhoven", area:"Bleekweg · Centrum", tier:2, cost:"€20–35 pp", vibe:"Brewery",
      desc:"A genuine city brewery with a wide range of house beers, good food and cool authentic surroundings. Plenty of seating around the bar or out on the terrace.",
      placeId:"ChIJTdEwlv3YxkcR-QZQLGAgFk8", q:"Stadsbrouwerij Eindhoven",
      web:"https://stadsbrouwerijeindhoven.nl/", insta:"https://www.instagram.com/stadsbrouwerijeindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNmOcl1hO6G9jsKKVmgynvdgeeUX9EvM6aoB7RLj5eIAAu0f5D3gsz-f4Ixn4PSz_FtHFBELCo60Ic6S_k_8GJmPVRq1z0OIq8HzihpCuoAA9Rch0SS-kWv9FSekRnzoiQVrxO5ZKqkgFUp=s1600-w1000" },

    { name:"Dinner in Motion", area:"Piazza · Centrum", tier:4, cost:"€60–80 pp", vibe:"Immersive",
      desc:"A 6-course immersive dinner: 360° projections, light and music turn the room into a new world for every course, with cocktail & wine pairing. A spectacle for a special night.",
      placeId:"ChIJ-05zsjLYxkcRVJUL5GjKgn4", q:"Dinner in Motion Eindhoven",
      web:"http://www.dinnerinmotion.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZPPbq_xNTP8ypTMkmAW_-67izgT5Nk_AuOP8a8a1oU7DIdO7-JUlOtZBBnktyoxf1zv6vJbMD6MRVDdsz69rqTA1BLrHASFW3vYADZMTYF65zfwOY4OpsMsJ1nz9ED2mLWh4-faLuIh7EIb=s1600-w1000" },

    { name:"VANE Restaurant & Skybar", area:"Vestdijk · Centrum", tier:4, cost:"€40–70 pp", vibe:"Rooftop",
      desc:"15th-floor rooftop with panoramic city-and-trees views and inventive cocktails. The restaurant below serves refined courses against the sunset. The spot for celebrating.",
      placeId:"ChIJ1Xjj2RzZxkcRKf5A0IFA_K8", q:"VANE Restaurant Eindhoven",
      web:"https://www.vane-eindhoven.nl/en/", insta:"https://www.instagram.com/vane_eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMcRNsPYi5ybY1DLvsQIs6xj-Vy73PW3_kDmqdVBv5N5yytMqjPyqoQNxdZRPLqUDq60TqW8gWxol_EdoQJzf0V_yGPwQPspaLXM6weyKGqabGExq88V_rlYmrAQcCzAqH_MlIOhKCLU2wHk4U=s1600-w1000" },

    { name:"Restaurant Kazerne", area:"Paradijslaan · Centrum", tier:4, cost:"€40–70 pp", vibe:"Design venue",
      desc:"Inside a former 1825 military barracks — restaurant, hotel and rotating art/design exhibition in one. Large open kitchen, dramatic custom lighting, chef's menus.",
      placeId:"ChIJMe6p8gPZxkcRerd8jOE-hGU", q:"Restaurant Kazerne Eindhoven",
      web:"https://kazerne.com/eat-drink/bar-bistro-kazerne/", insta:"https://www.instagram.com/kazerne_eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZP-5Eh33Zs_n3DDdSlkcHaJ_ftjDN0OKdRJM1MC-xFuqWoufKvWEdwN68CkzugTOdTRIqbOPPDKogwVSu1wTH0Q71a2OkOlc-kRN3P04eeea8Q4WTdbAbegvaggBsQ3yWpbCZCcXRGnCUydjWs=s1600-w1000" },

    { name:"Restaurant De Luytervelde", area:"Woensel-Noord", tier:4, cost:"€45–80 pp", vibe:"Hidden gem",
      desc:"A little gem hidden between houses just above Eindhoven, in a lovely building. Colourful, creative, beautifully-plated French-leaning courses and standout sauces. Reserve — it fills up.",
      placeId:"ChIJTxHixwHcxkcRV57XJwjdyZE", q:"Restaurant De Luytervelde Eindhoven",
      web:"http://deluytervelde.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNP37ieFY4P6b77xbe1rda6dRuHonYszjIuL2DWpoqqN_iCTvTgnEWiG3XA3WRl72i1oV5l0Kc4I0xkz4GjtOtsPNBwy4OmCCQIopzHvNiX-9wPs2tO6pjnBZRVMsvms8gZDT3j-aekmVIUl_g=s1600-w1000" },

    { name:"Matsu Beef Atelier", area:"Strijp-S", tier:4, cost:"€60–90 pp", vibe:"Wagyu & wine",
      desc:"A beautiful beef atelier devoted to wagyu and fine wines. High-quality, beautifully-prepared tasting menus — aburi nigiri on crispy rice, tartare, premium cuts. A real occasion.",
      placeId:"ChIJIb7BFmvZxkcRw3bFlZac0xI", q:"Matsu Beef Atelier Eindhoven",
      web:"https://www.matsu.nl/", insta:"https://www.instagram.com/matsu.eindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOHPX-7RwYBM71xPRYUZ7TeKJg_jQ6WYp-DYnN7M9DZxQNvVEyfidjxAJVIvir7mZby4Tjz4RFQnjiBJFLcsmVsTMAXeJ1NoPrrCkkLnU5oWTtN87CiZxmRT8J-3xOEXTfH7ZY0iZNx0WpLfUKk0AkGCA=s1600-w1000" },
  ],

  activities: [
    { name:"Barkeet Arcade Bar", area:"Stratumseind · Centrum", tier:1, cost:"€5 + drinks", vibe:"Arcade bar",
      desc:"Pay €5 for a whole day of arcade machines, board and table games, plus a rooftop terrace over the river. Brilliant for a group or a low-key date.",
      placeId:"ChIJI4q667TZxkcRQKd-Slcft18", q:"Barkeet Eindhoven",
      web:"https://barkeet.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMez0Mb-Ux9UowFT8_W3hIW3HRIA0_sZdz4R3LIf46WwHz1N4yT59_IYa5y0z6qGLif3JcCBJafizAqDVAVsWiu8jHSo-L8PeAmHuUHpW4QZ15WO_TVD-2RxhO7s0g4gkpwZJoaBExsDZkIGqMbPyZTIQ=s1600-w1000" },

    { name:"Op Noord — Outdoor Minigolf", area:"Eindhoven Noord", tier:1, cost:"€8–15 pp", vibe:"Minigolf",
      desc:"Well-kept outdoor minigolf with a café-bar attached. Friendly staff, sunny-afternoon energy — a proven team-building or first-date warm-up.",
      placeId:"ChIJ98B3vrLexkcRD1x0QfA6A8c", q:"Op Noord Eindhoven",
      web:"http://www.opnoord.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMAV58-pTNWvQXeJCvkAgWTmSpi4Gvk9ALwOm6B50qId5xLNQhmTkpK8x1DCKgLB58M2tSwJxMT3uZ94zaOlbd458KJY1Pf57S0O2gHeEeji5Waab496IW9gcmZhng6J59VAGQOj6ZqeioZKg=s1600-w1000" },

    { name:"Glowgolf", area:"Vijfkamplaan", tier:1, cost:"€10–15 pp", vibe:"Glow minigolf",
      desc:"Glow-in-the-dark 3D minigolf with arcade and a bar — surprisingly great fun for grown-ups, statues and trippy black-light everywhere.",
      placeId:"ChIJCVu7f7HexkcROOq6B_oh22U", q:"Glowgolf Eindhoven",
      web:"http://www.hollywood.nl/eindhoven", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZN8hBN_X1g1pI-0qpuC4zzoAn0wAopRZX59vb55R9UabPi9eNDsBXT-puyUpZp-tJ3EwjArCoLgnLP-XyQYrvU5Kwfa4AqlM3aj8EMg-CHKTDhVuzbTpZUQH7QWS9q56S0eDcaERlqc5Q8mmTmcqLRy=s1600-w1000" },

    { name:"Peakz Padel (Beursgebouw)", area:"Centrum", tier:1, cost:"€10–20 pp", vibe:"Padel",
      desc:"Padel courts right in the centre with a bar to hang out afterwards. Easy to pick up, genuinely fun for a mixed-ability group.",
      placeId:"ChIJBVYE-ObZxkcRo2Bgp29N27A", q:"Peakz Padel Eindhoven Beursgebouw",
      web:"https://www.peakzpadel.nl/locaties/beursgebouw", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMXXXeR93sr7h1RvWR1Z0jgshXiD79JFEYvWqBkm8noktBzpaWf1CLKaBuMxQBEp4PCDn3Fbjk3DwMz4EJTu2qZ1kUw3IAU3BWliB0FdOFOjmhfoZfsllVVwvuiN8i-mQXL4eddTGO0_uPLezI=s1600-w1000" },

    { name:"Laser Quest", area:"Oude Stadsgracht · Centrum", tier:1, cost:"€10–18 pp", vibe:"Laser tag",
      desc:"Laser tag in a big, twisty multi-level maze, plus pool tables and beer. Get a printed stats sheet at the end — great for competitive groups.",
      placeId:"ChIJHypxcgLZxkcRSwzljbFgFWs", q:"Laser Quest Eindhoven",
      web:"http://www.lqehv.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMOZ3iereFD_wK9TSfbUplezAYnr9i8jh4mRKDMZYZaUhRWeEQ3iQji3sELo3ySckHRFqzeONqmpR5bxapLB04i0a0Sfr5HrgjavJXErrz6DIqdImm7SQrqLsAhmpUWc9rBSx1Wf45HUSnd_w=s1600-w1000" },

    { name:"E.S.H. Da Vinci — Archery", area:"Amazonenlaan", tier:1, cost:"€15–25 pp", vibe:"Archery",
      desc:"Archery club with beginner courses, indoor and outdoor (up to 90 m). Members call it 'farmer meditation' — focus, friendly competition and a calm head.",
      placeId:"ChIJKwn5N9rYxkcRNEqD1UXnu1o", q:"ESH Da Vinci Eindhoven",
      web:"http://www.eshdavinci.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNJ6PhbaO7N_P9vkLuOy79jgy4J-A50xrMxRgclCXMaKdf3wK4kQ00Z8FPUPDCa-KPuWbx7PUDc1HwblKeY4IpL4U_iCUqDgnuoYysmzU4mmj5jdiJpJAaZ8HgFw5yosSyq9TFef8HPsQqnwHk=s1600-w1000" },

    { name:"Rabauw Brewpub", area:"Strijp-S", tier:2, cost:"€15–30 pp", vibe:"Craft brewery",
      desc:"A small craft brewery with a great range of stouts and IPAs on tap, free pool and brilliant vibes. Do a tasting flight and settle in.",
      placeId:"ChIJFZwIIZjZxkcRc-H1X_-1pIY", q:"Rabauw Brewpub Eindhoven",
      web:"https://rabauw.org/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZPMpQ8rxwon3wS-GsnfR7UmfTegJ4ZU_kuoVd3DaENHWWaTp-qumzVaH4xh53u_WWIPDaPJCpbAXGrbKUKC8CgrPmPZEQonxBIABXvR-O8KvIWMHCefJtsKvY2_GZh-IUL4aiCxwzijcX3w5gUg6GUqqg=s1600-w1000" },

    { name:"Stadsbrouwerij — Beer Tasting", area:"Bleekweg · Centrum", tier:2, cost:"€15–30 pp", vibe:"Brewery",
      desc:"City brewery with flights of house beers and food — a relaxed, sociable base for the start of an evening with friends or colleagues.",
      placeId:"ChIJTdEwlv3YxkcR-QZQLGAgFk8", q:"Stadsbrouwerij Eindhoven",
      web:"https://stadsbrouwerijeindhoven.nl/", insta:"https://www.instagram.com/stadsbrouwerijeindhoven/",
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNmOcl1hO6G9jsKKVmgynvdgeeUX9EvM6aoB7RLj5eIAAu0f5D3gsz-f4Ixn4PSz_FtHFBELCo60Ic6S_k_8GJmPVRq1z0OIq8HzihpCuoAA9Rch0SS-kWv9FSekRnzoiQVrxO5ZKqkgFUp=s1600-w1000" },

    { name:"Paint Spat — Neon Paint Fight", area:"Kronehoefstraat", tier:2, cost:"€25–40 pp", vibe:"Glow painting",
      desc:"A glow-in-the-dark neon paint-fight room (rated 4.9) — chaotic, creative, hilarious. You take your canvases home. Totally different from the usual night out.",
      placeId:"ChIJqwrc5d7ZxkcRa2TdfJzSvvQ", q:"Paint Spat Eindhoven",
      web:"https://paintspat.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZN-1EWDaHp1lWeOfBVgTyCyFH3FVufNnbniaByi5XBRy5VlS6XFa7W2sSrSJ_os0f48FyhIVXMN3GgC8kBpL-zvctmpoLjtWoIzyEHnlIRX8XFAyiac6tEtFgvn4Sseu4iIWi9lokRdEfEPuI3lCfAq=s1600-w1000" },

    { name:"Rembrandt van Wine — Sip & Paint", area:"Klokgebouw · Strijp-S", tier:2, cost:"€30–45 pp", vibe:"Paint & wine",
      desc:"Sip & paint with an open wine bar (rated 4.7): music, colour and unlimited wine while you make a canvas you're weirdly proud of. Ideal first date or cosy group night.",
      placeId:"ChIJkz7QTwLZxkcRmy2uSIygBc0", q:"Rembrandt van Wine Eindhoven",
      web:"https://www.rembrandtvanwine.nl/sip-and-paint-eindhoven/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZO8uDWTf2u1bqqXgprrfnd2e0ImMMExL14GbfoJeNWltxgdv82CqMaX3Z53JaSh-OwixVX13hYjsYyXBoiaKyB-uAVRePAlPpHmsqmAYpxEPSHTUs4HM7dEgYKlfduI9rTuQBjwzeLe7QQSRBpZVcxt1g=s1600-w1000" },

    { name:"Hezemans Indoor Karting", area:"Vijfkamplaan", tier:2, cost:"€20–35 pp", vibe:"Karting",
      desc:"Indoor electric go-karting plus an axe-throwing bar and arcade under one roof — the classic adrenaline group outing with drinks to follow.",
      placeId:"ChIJm98of7TexkcR8mvHswMPxno", q:"Hezemans Indoor Karting Eindhoven",
      web:"http://www.hezemans.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZP7ktZzuGCEbWZ5uKMi-970EBqiA6wM3w_d7yG8cWrDXIm7uvcekKZ_JeffNcZmaqkjbgt3OzzzJuQHXi9qN1l-Hc_E1v7GymIPQa03KkHcsPLKNbt1sHQpcYOzJStgOjlVQLubi-h_wYkZ1A=s1600-w1000" },

    { name:"Another World VR Arena", area:"Rechtestraat · Centrum", tier:2, cost:"€20–35 pp", vibe:"VR",
      desc:"Open free-roam VR arena where you can play co-op games and grab a beer right beside the action. Easy, social, central.",
      placeId:"ChIJJ8O3JwvZxkcR1gj4Bn8-6nk", q:"Another World VR Arena Eindhoven",
      web:"https://eindhoven.another-world.com/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMNoY8kDmtam8MrfX9xiUdTQecZSjXFxxcGxgR_uk_LIr2pHWg2Z-eBLeTktUQD5is7S_BBYQm8ZTny3sVpu3ju78smywsFkG6CRp7ePQvVLKOfGcurnvzIGrjJIK_tc1rSO3KUOj272h-vT3bBAMIsbg=s1600-w1000" },

    { name:"Klimrijk Brabant — Tree Climbing", area:"Veldhoven", tier:2, cost:"€20–30 pp", vibe:"Forest adventure",
      desc:"A high-ropes adventure park in the forest: courses through the treetops, plus ATVs and e-bikes. Fresh air and real adrenaline, great for a daytime team day.",
      placeId:"ChIJ74UMmoTQxkcRCYQ8ZnqMUgc", q:"Klimrijk Brabant Veldhoven",
      web:"https://www.klimrijk.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNB6WW07aYv9ruufsHfrzibcJOO7wsPOkr54uN5aOlAAvV_PvVh1EGVyQ-DRmfbc_wtTsMj7kSjN5lQLHjUyWPiR7EqzahLIRLs6issZHZEEa6mlmTsMQtCH3K5Ucpb0LBBZsv1IJrGtMIVUQ=s1600-w1000" },

    { name:"Clay Atelier — Pottery Painting", area:"Hoogstraat · Centrum", tier:2, cost:"€25–40 pp", vibe:"Ceramics",
      desc:"Relaxed ceramic-painting workshop (rated 4.9) with a drink and a pastry — clear guidance, lovely shop, two-week pickup of your finished piece. A great date.",
      placeId:"ChIJwVE6KAnZxkcR9XSsKC44pBc", q:"Clay Atelier Eindhoven",
      web:"https://www.clayateliereindhoven.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNeLKSHRibH2HuAsSKCT22vU7Xrnhss-eXBJXt05ulDyOPSoMArH9yMZviHjrXXNHElFUS_eRQPtFyDn51FFM_YkEu84bhdb9jF6AR_cDSExJhrviyp-oi3lL_ivjO5Hw71DJFyySsRiKpGUILA5VPi=s1600-w1000" },

    { name:"Seven and Half Ceramic", area:"Lijsterbesstraat", tier:3, cost:"€30–45 pp", vibe:"Ceramics studio",
      desc:"Intimate wheel-throwing and ceramics workshops (rated 5.0) with patient, skilled hosts. A calm, hands-on afternoon that turns into a proper hobby for some.",
      placeId:"ChIJf_dE2wjZxkcRrVeVBU9JTBs", q:"Seven and Half Ceramic Eindhoven",
      web:"https://seven-and-half-ceramic.com/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZPdCYoPisCK_PketQAXKfKfaNPblmWXGh2zeQlj50j2vNRtGWyPzrtJivw9ETfHpdTcU-vtaLkj4Y1MdeuPQD80uxCA8N6Tg0GecLCH-IrP-JgJhI9FbDazWyX_jEhWJ0YJfvyHL196mfSeTzc=s1600-w1000" },

    { name:"The Revellers — Cocktail Workshop", area:"Stratumseind · Centrum", tier:3, cost:"€15–40 pp", vibe:"Mixology",
      desc:"A 5.0-rated cocktail bar run by two mixology nerds — bespoke drinks built around your taste, plus hands-on workshops. Perfect for a group or a date.",
      placeId:"ChIJFwFHemHZxkcRcMpFuWPuTRQ", q:"The Revellers Eindhoven",
      web:"http://therevellers.bar/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNc6Ws2gEsj_xgGClXgWU6k3euYuWEDtvRODq-gW0-Ftt2nxpKrmpt9gOcigfolamjsXBqOp10W4aPcaZm-y1DhJScCTA5yqxIG8stYYByiRNcO79Z62hYKact67QX-HdeeYuSWDT39vUpTZQ=s1600-w1000" },

    { name:"Twist — Cocktails & Tapas", area:"Scheldestraat", tier:3, cost:"€25–45 pp", vibe:"Cocktails",
      desc:"A cocktail-and-tapas spot with a big wall of spirits, a creative chef from Alicante and the option to do a workshop. A hidden gem between the centre and the stadium.",
      placeId:"ChIJm_G0GifZxkcR4ExenHFOO7c", q:"Twist Hospitality Eindhoven",
      web:"https://www.twist-hospitality.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNW4RnPQjH0ozeFYpvMSWARvBUgssXUR6ob2ooCSPWt-tuRn4EAqTVBAAV98l4WFWJLwR4U_E61rCMJj8TLn43Rde8kQ96jI7U32zc-3zMv9kHpBSS9tXXRj-jOpSKorJEws_XVD4366Rx7=s1600-w1000" },

    { name:"WRKSHOP — Team Activities", area:"Willem de Zwijgerstraat", tier:3, cost:"€25–45 pp", vibe:"Team building",
      desc:"Turn-key group experiences: pop-art workshops, karaoke, pub games and beer quizzes with hosts who keep the energy up. Built for team days.",
      placeId:"ChIJQ75K0QXZxkcRccLSWQBAXzc", q:"WRKSHOP Eindhoven",
      web:"https://wrkshop.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNeZtj_cniTPph4doCCdenUtuvGADT7LSvUZHWKwW53GHkPFaG0JLqvQ1aqmIyhP41YQw8bUTAA79SXGh1W2eu6oxZnF8IPUzDxF9J9aMU4K8BazEdE6VqjSvG1Z_bZB2pJzC2qd-PEMsX61Q=s1600-w1000" },

    { name:"Enversed VR Experience", area:"Prof. Dr. Dorgelolaan", tier:3, cost:"€25–40 pp", vibe:"VR",
      desc:"A premium VR arena with co-op shooters, virtual museums and escape-style missions — well-run for groups, with snacks and drinks brought to your booth.",
      placeId:"ChIJ71qRvWvZxkcRu7PNs3Twe4M", q:"Enversed Eindhoven",
      web:"http://www.enversed.com/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNNFIbTIKJ-6NJLLaQq7tANfclURnzECLGJBIWEmA-X6FuKvFBMnfbzw906YBHwSy7TtOgBGyChQL3nGAwn6f1sbnH3P_hPSse5H1-MAXYlPCY_TJg2Pw3XARfkjKOCaqWNJ_paWu4meCKTa8k=s1600-w1000" },

    { name:"THE RAGE — Smash Room", area:"Eindhoven Noord", tier:3, cost:"€25–45 pp", vibe:"Rage room",
      desc:"A 5.0-rated rage room: smash everything in sight with a baseball bat to your own playlist. Safe, well-run and a genuinely cathartic group laugh.",
      placeId:"ChIJQ6dwwUnfxkcRZBLcRljJjy0", q:"THE RAGE Smash Rooms Eindhoven",
      web:"https://therage.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMYB93YFgK-TSh-x3bRbKXYwRJxMlMa5YvZS58nBDEfg8JSGS2hPXEMhsutlO2G5-yJTpQhNCKtSpmrvBh3V0DaTL0RrI6W3rFUsY6bGxqTLmTCSrRjBu48dQ9BTNvXBTuwbYricu5jZsiwucBRIlyk0w=s1600-w1000" },
  ],

  trips: [
    { name:"Loonse en Drunense Duinen", area:"Drunen · ~40 min drive", tier:1, cost:"Free · ~€5 parking", vibe:"Nature day",
      desc:"The closest thing the Netherlands has to a desert — drifting sand dunes, pine forest and heath. Borrow the free bikes, picnic on the dunes, finish at a forest café. A pocket adventure 40 minutes from home.",
      placeId:"ChIJW76EGzG-xkcRdPJq1UCR7CY", q:"Loonse en Drunense Duinen",
      web:"https://www.natuurmonumenten.nl/natuurgebieden/nationaal-park-loonse-en-drunense-duinen", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMMsA4vKBAOcc--w0qglxNiPDl3eKzc9B7iNq5cm3yb0GFuGP3RBfBAKLsvMSPedRnoelA9bcNP-ozqU6S0LB7zWgI-OWB42qzqo3bjgU3E7H5IR3wyLqxlA-rel9HiB9WlOsYZhwNCczCGUw=s1600-w1000" },

    { name:"Biesbosch Boat Trip", area:"Drimmelen · ~1 h drive", tier:2, cost:"€20–35 cruise", vibe:"River wilderness",
      desc:"Drive out to Drimmelen, then glide through one of Europe's last freshwater tidal wetlands by boat — beavers, kingfishers, silent creeks. Book the cruise with lunch on board and make a full day of it.",
      placeId:"ChIJ70X4o1WcxkcRi42lHL80N5k", q:"Rondvaartbedrijf Zilvermeeuw Biesbosch Drimmelen",
      web:"https://zilvermeeuw.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNaCqW4TL1gO6WhL1zoXkw-XAVmTVgp4Hh14-3R53q4BIFDLpawCouaAO5zRxgJy-twK0f6Eb7hE2eSaGhoaI2OjHbA_dA4klxtag-KCiwKTb9E3CLtC2Mt_iNtODeYDmRoh6t0Gg0-8Xbf8Q=s1600-w1000" },

    { name:"Den Bosch — Canals & Cathedral", area:"'s-Hertogenbosch · ~30 min train", tier:2, cost:"€15–30 + travel", vibe:"Historic city",
      desc:"Hop the train to the Netherlands' finest Gothic cathedral, then cruise the hidden Binnendieze canals beneath the old town and devour a Bossche Bol (giant chocolate cream puff). Easy, classic, close.",
      placeId:"ChIJB55Bu_fuxkcR0yjSfy05V78", q:"Sint-Jan Cathedral Den Bosch",
      web:"https://www.sint-jan.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZOnauzm2mRmIs4pRBR-e5Ja8FZD5FcLnqmEr6wfy_bCjQkfj2dvYZYuiiOrhWCiCHjeyQcqLyEGAFH-WO5-cdrQjWWhQE0AI-4V7ej0en2OUALDXhHdr_8D7Ne-IVk-WKQUTZa-1jlKfgmlVhU=s1600-w1000" },

    { name:"Utrecht — Canals & Dom Tower", area:"Utrecht · ~1 h train", tier:2, cost:"Travel + city", vibe:"Canal city",
      desc:"The Netherlands' tallest church tower over a city of two-level wharf canals, with terraces right at the water. Climb the Dom, drift the canals, café-hop. A prettier, calmer Amsterdam.",
      placeId:"ChIJgf7hSkVvxkcRNQQW-7nl0T8", q:"Dom Tower Utrecht",
      web:"https://www.domtoren.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZM5Lk3nwFQy3M6O9aVbJ2O2fnDgWG5tjDN7Nuun-oB6GuDR00GhaQTBQWsfFxkI8msh5MJGC990v_ZUuSzUH32uvj-TwREKdbBofqA3xZai0Ibc24ELlIhj1LlQG-N8W8ZlNv_Icb8=s1600-w1000" },

    { name:"Rotterdam — Markthal & Cube Houses", area:"Rotterdam · ~1 h 15 train", tier:2, cost:"Travel + city", vibe:"Architecture",
      desc:"The Netherlands at its most futuristic: graze the vaulted Markthal food hall, gawp at the tilted Cube Houses, then walk the river and the port skyline. A design-lover's day out.",
      placeId:"ChIJexHTc1wzxEcRGPuXpxt5bkM", q:"Markthal Rotterdam",
      web:"https://www.markthal.nl/en/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMucSZp1wt_ExiGwwbRhIhcG8maLnHJl2jROnGkWhaxhs3Bkn2q2wsOr1NBENvGg0-83D6ZqAUgut34ETCqA5fTxIH5JXEne4uL1VvMWXCKaeqAhB8HtZr5LQNBmsp9C8i3aJrxoSd1Sofa51k=s1600-w1000" },

    { name:"Maastricht — Old Town", area:"Maastricht · ~1 h 15 train", tier:3, cost:"Travel + city", vibe:"Burgundian city",
      desc:"The oldest, most Burgundian city in the country: grand squares, a bookshop inside a medieval church, riverside terraces and great food. A proper romantic day trip south.",
      placeId:"ChIJUYk7-43pwEcR6zckiME_EKA", q:"Vrijthof Maastricht",
      web:"https://vrijthofmaastricht.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNAQ56VXVd8G-ZJi8BIDvp4_Cglv0Hgx0JolKKnwYDAqfqNo4Zm3phavNMyWmzvmzFYMxIYVJqTU25kE9XAEL87u-H7ExaEPNoJEQmq5l44ftrwsvUqM4yhUCnWSkieZ6vN8r5wAGi0PL2BBg=s1600-w1000" },

    { name:"Efteling Theme Park", area:"Kaatsheuvel · ~45 min drive", tier:3, cost:"~€44 ticket", vibe:"Theme park",
      desc:"One of Europe's oldest and most beautiful theme parks — fairytale forest, world-class coasters, obsessive detail everywhere. A full, joyful day of being a kid again.",
      placeId:"ChIJB0P0r6mWxkcRmrhc7bHaO0Q", q:"Efteling Kaatsheuvel",
      web:"https://www.efteling.com/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZN2erL6ZToinIuQIySK0Vjmql7p8jCp4w9hKaZ9pGmuJ4o3QexvVQsXjZplJZVFnAmiKGyxlyJPrRwAaNqGCzGQNaAOQT9Dw5h72lP-Hc7kburxfVEN28Z6cmlQIxCPgMDyrBGS80eZ8_KLfg=s1600-w1000" },

    { name:"Antwerp — Grote Markt", area:"Belgium · ~1 h 15 drive", tier:3, cost:"Travel + city", vibe:"City break",
      desc:"Cross into Belgium for a magnificent old square, a soaring cathedral, the diamond and fashion quarters — and frites, waffles and proper Belgian beer. A different country before dinner.",
      placeId:"ChIJY6eTP_b2w0cRnvPtAhhlczY", q:"Grote Markt Antwerp Belgium",
      web:"https://www.visitantwerpen.be/en", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMRCRvNr-uQdT7nL-veODEIRMRYnsz5ticyIHDJlCwtNV1Oy8iKslTou4Ik4lcIMURxa8fvo6TpuLaQh6qJOGYTqwpYANvuabnne3VXfSt51LvUuV7hYgzT6xgiEpge9yFB-Wb_K-om23CkrlI=s1600-w1000" },

    { name:"Kröller-Müller & Hoge Veluwe", area:"Otterlo · ~1 h 15 drive", tier:3, cost:"~€40 park + museum", vibe:"Art & nature",
      desc:"Europe's largest sculpture garden and a huge Van Gogh collection, set inside a national park you cross on free white bikes. Art, forest and heath in one unforgettable day.",
      placeId:"ChIJ59IECAaxx0cRXiACiCogHF8", q:"Kroller-Muller Museum Otterlo",
      web:"https://krollermuller.nl/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZMu211t5-1a8SBSI-Pl7dBs0ecL-sBGkGD5MSseOnNY0yg5eeCahQvZkm9DqeQmsLF0aK-GrK8_tAByAH4222Lru0aMfFmsQmcXCpr2Naf8ft1-d_c_a27pHp0jQMu1hVpHkrr7Ao5es5ZbQw=s1600-w1000" },

    { name:"Cologne — Cathedral & Old Town", area:"Germany · ~2 h drive", tier:4, cost:"Travel + city", vibe:"City break",
      desc:"The big one: a monumental Gothic cathedral that towers over the Rhine, a riverside old town and traditional brewhouses pouring Kölsch. A full-day border-crossing adventure.",
      placeId:"ChIJLz2cNqUlv0cRxqnjljiR7Ck", q:"Cologne Cathedral Germany",
      web:"https://www.koelner-dom.de/", insta:null,
      img:"https://lh3.googleusercontent.com/place-photos/AJRVUZNF_uEbuius1mhl5QICmP47Dr2ng7XY4O3B4fY-i9Utw7equru-X5UhCVo9XvgnkRK6usUVzNZRi8bFjZZoI59hBJwAKNeKb_t68bO-n4ON36j9ibGgrkzvyjjVBRGhusiSdmiDMMYc-4Lwuop6fH2Yeg=s1600-w1000" },
  ]
};
