/* Eindhoven Nights — places data
   tier = price bucket for sorting (1=cheapest ... 5). 'free-ish' uses 1.
   img = Google place photo (loads live in browser). maps link built from placeId. */
window.DATA = {
  restaurants: [
    { name:"Takumi Ramen", area:"Nieuwstraat · Centrum", tier:1, cost:"€15–25 pp", vibe:"Ramen",
      desc:"The best ramen in town — rich, authentic tonkotsu broth and a cosy buzz. Expect a short queue; no reservations, just go and slurp.",
      placeId:"ChIJjcN1hG3ZxkcR54oXm6RmpuQ", q:"Takumi Ramen Eindhoven Nieuwstraat",
      web:"https://www.takumiramennoodles.com/nl/eindhoven-nieuwstraat/", insta:null,
      img:null },

    { name:"Wasven Gasterij", area:"Tongelre", tier:1, cost:"€10–18 lunch", vibe:"Farm-to-table",
      desc:"A working bio-farm with its own veg garden and bakery, tucked between woods. Most of the plate is grown on-site. Walk it off in the forest after.",
      placeId:"ChIJu4vXyb_YxkcRBa9_GYw0GPs", q:"Wasven Gasterij Eindhoven",
      web:"http://www.wasven.nl/", insta:"https://www.instagram.com/wasven/",
      img:null },

    { name:"Down Town Gourmet Market", area:"Smalle Haven · Centrum", tier:2, cost:"€15–25 pp", vibe:"Food hall",
      desc:"A buzzing SE-Asian-street-market-style food hall — many kitchens under one roof, plus an all-you-can-eat option. Loud, lively, perfect for a group with mixed cravings.",
      placeId:"ChIJtfSa9wLZxkcR_PsNpWW8r48", q:"Down Town Gourmet Market Eindhoven",
      web:"https://downtowngourmetmarket.com/", insta:"https://www.instagram.com/downtowngourmetmarket/",
      img:null },

    { name:"Hout", area:"Strijp-S", tier:2, cost:"€15–25 pp", vibe:"Pizza",
      desc:"Neapolitan pizzeria in a big, high-ceilinged room. Outstanding dough, proper tiramisu, fast service. Works for a date or a crowd.",
      placeId:"ChIJo4RDOADZxkcRKR6Y-osYKrA", q:"Hout Eindhoven",
      web:"https://www.houteindhoven.nl/", insta:null,
      img:null },

    { name:"Pummaró", area:"Sint-Trudoplein", tier:2, cost:"€15–25 pp", vibe:"Pizza",
      desc:"Cosy neighbourhood pizzeria with a little garden and a warm Italian welcome. Soft, well-made pizza and a family vibe.",
      placeId:"ChIJU52dThHZxkcRWFYxe35wnE4", q:"Pummaro Eindhoven",
      web:"http://www.pummaro.nl/", insta:null,
      img:null },

    { name:"superMARKT restobar", area:"Woenselse Markt", tier:2, cost:"€15–25 pp", vibe:"Hidden gem",
      desc:"A little gem in a chaotic neighbourhood. Small simple menu, fresh ingredients, a self-imported list of small French wines and a great sound system.",
      placeId:"ChIJU7wFBSHZxkcRysOMeNvJHK4", q:"superMARKT restobar Eindhoven",
      web:"https://supermarkteindhoven.nl/", insta:"https://www.instagram.com/supermarkt.eindhoven/",
      img:null },

    { name:"Otomoto", area:"Vrijstraat · Centrum", tier:2, cost:"€20–35 pp", vibe:"Listening bar",
      desc:"A Japanese-inspired listening bar: natural wines, dumplings and small plates, vinyl all night. Menu changes with guest chefs. No bookings — one of the chillest rooms in town.",
      placeId:"ChIJ8azhtzzZxkcR9kL-VXcaqVM", q:"Otomoto Eindhoven",
      web:"https://www.otomotosocial.com/", insta:"https://www.instagram.com/otomoto.social/",
      img:null },

    { name:"Tres Tapasbar", area:"Emmasingel · Centrum", tier:2, cost:"€20–35 pp", vibe:"Tapas",
      desc:"Spanish tapas in the centre, made for sharing and good for groups. Lively, diverse menu with veggie options.",
      placeId:"ChIJc6ovwJHZxkcRoiO-Oza7Lpc", q:"Tres Tapasbar Eindhoven",
      web:"https://www.trestapasbar.nl/", insta:null,
      img:null },

    { name:"La Casera", area:"Keizersgracht · Centrum", tier:2, cost:"€20–35 pp", vibe:"Wine bar",
      desc:"An Italian wine bar (rated 4.9): cured meats, cheeses and every wine by the glass, with warm, expert recommendations. Snug and romantic.",
      placeId:"ChIJ0ZPNZwDZxkcRuowD5c579_E", q:"La Casera Eindhoven",
      web:"https://la-casera.nl/", insta:null,
      img:null },

    { name:"Le Cozy", area:"Kleine Berg · Centrum", tier:2, cost:"€20–30 pp", vibe:"French bistro",
      desc:"An oldie on lively Kleine Berg. Bistro chairs, classic French menu, oysters and escargots — a corner of Paris for people-watching on the terrace. Romantic and reliable.",
      placeId:"ChIJFZ4P9QTZxkcRne0pMpOvYTc", q:"Le Cozy Eindhoven",
      web:"https://lecozy.nl/", insta:"https://www.instagram.com/lecozy.eindhoven/",
      img:null },

    { name:"Trattoria Mangiare", area:"Kleine Berg · Centrum", tier:2, cost:"€20–30 pp", vibe:"Italian",
      desc:"One of the best Italians in town, warm and welcoming, great for a birthday or a bigger group. Book ahead — it fills up.",
      placeId:"ChIJK-qbRwTZxkcR_Pc4DhvbWQw", q:"Trattoria Mangiare Eindhoven",
      web:"http://www.trattoriamangiare.nl/", insta:null,
      img:null },

    { name:"1910 Restaurant", area:"Willemstraat · Centrum", tier:3, cost:"€25–40 pp", vibe:"Surprise menu",
      desc:"Warm fresh bread, cosy lighting and a much-loved surprise menu that's outstanding value — order as many courses as you dare. Beautiful interior, terrace, strong wines by the glass.",
      placeId:"ChIJAbqIZQXZxkcRuI4W-gIblu8", q:"1910 Restaurant Eindhoven",
      web:"https://1910.nl/", insta:null,
      img:null },

    { name:"Mrs Park", area:"Meerhoven", tier:3, cost:"€25–40 pp", vibe:"Lakeside",
      desc:"Lakeside spot near the airport with a gorgeous waterfront view. Diverse menu, dog-friendly, open late every day. People wander in off a walk and stay for wine.",
      placeId:"ChIJezjSEQLbxkcRtzOhu3m8zpo", q:"Mrs Park Eindhoven",
      web:"https://mrspark.nl/", insta:"https://www.instagram.com/mrspark.nl/",
      img:null },

    { name:"Radio Royaal", area:"Strijp-S", tier:3, cost:"€30–40 pp", vibe:"Industrial",
      desc:"Set inside a former Philips power house — raw industrial steel, vintage furniture, foosball. A 3-course menu of refined twists on classics, great price/quality.",
      placeId:"ChIJbZCEA2vZxkcRodV4oBGF6SM", q:"Radio Royaal Eindhoven",
      web:"http://radioroyaal.be/", insta:"https://www.instagram.com/radioroyaal/",
      img:null },

    { name:"Usine", area:"Lichttoren · Centrum", tier:3, cost:"€25–40 pp", vibe:"Industrial",
      desc:"Cavernous industrial-chic space opposite the iconic Lichttoren. Reading corners, exposed concrete and steel, all-day dining with a huge variety of seating. A landmark.",
      placeId:"ChIJVVUVKBvZxkcRGuF6xJVe7g4", q:"Usine Eindhoven",
      web:"https://usine.nl/", insta:"https://www.instagram.com/usine_eindhoven/",
      img:null },

    { name:"Parkpaviljoen Philips de Jongh", area:"Philips de Jongh Park", tier:3, cost:"€25–40 pp", vibe:"In the park",
      desc:"Literally inside a forested park. Beautifully renovated pavilion with a leafy terrace — eat, then walk or cycle straight into the green. Dog-friendly little slice of paradise.",
      placeId:"ChIJQYAXi1vZxkcRSSCr1N2qdj4", q:"Parkpaviljoen Philips de Jongh Eindhoven",
      web:"http://www.parkpaviljoenpdj.nl/", insta:"https://www.instagram.com/parkpaviljoenpdj/",
      img:null },

    { name:"De Watermolen van Opwetten", area:"Nuenen (10 min)", tier:3, cost:"€25–40 pp", vibe:"Historic mill",
      desc:"A restored historic water mill on the Kleine Dommel, on the edge of Nuenen and Eindhoven. South-facing terrace over the water and meadows; a footpath leads straight into nature.",
      placeId:"ChIJcSEzn6_YxkcRvdqOVfDAtpI", q:"De Watermolen van Opwetten Nuenen",
      web:"http://www.dewatermolenvanopwetten.nl/", insta:"https://www.instagram.com/dewatermolenvanopwetten/",
      img:null },

    { name:"De Mispelhoef", area:"Oirschotsedijk", tier:3, cost:"€25–40 pp", vibe:"Rustic farm",
      desc:"Heritage farm buildings with a big outdoor terrace and goats on the grounds. Cosy, lively and authentic with a wide menu. A long-time favourite near the airport.",
      placeId:"ChIJbSrqTozbxkcRSIiRKRLiIzU", q:"De Mispelhoef Eindhoven",
      web:"http://www.demispelhoef.nl/", insta:"https://www.instagram.com/demispelhoef/",
      img:null },

    { name:"Piet Hein Eek", area:"Strijp-R", tier:3, cost:"€20–35 pp", vibe:"Design icon",
      desc:"Restaurant, café, hotel, gallery and shop in the old Philips ceramics factory — the studio of the Netherlands' most famous furniture designer. Rooftop terrace, locally-sourced menus.",
      placeId:"ChIJq0lwKWbZxkcR1-k7fB61YTk", q:"Piet Hein Eek Eindhoven",
      web:"https://www.pietheineek.nl/", insta:"https://www.instagram.com/pietheineek/",
      img:null },

    { name:"Stadsbrouwerij Eindhoven", area:"Bleekweg · Centrum", tier:2, cost:"€20–35 pp", vibe:"Brewery",
      desc:"A genuine city brewery with a wide range of house beers, good food and cool authentic surroundings. Plenty of seating around the bar or out on the terrace.",
      placeId:"ChIJTdEwlv3YxkcR-QZQLGAgFk8", q:"Stadsbrouwerij Eindhoven",
      web:"https://stadsbrouwerijeindhoven.nl/", insta:"https://www.instagram.com/stadsbrouwerijeindhoven/",
      img:null },

    { name:"Dinner in Motion", area:"Piazza · Centrum", tier:4, cost:"€60–80 pp", vibe:"Immersive",
      desc:"A 6-course immersive dinner: 360° projections, light and music turn the room into a new world for every course, with cocktail & wine pairing. A spectacle for a special night.",
      placeId:"ChIJ-05zsjLYxkcRVJUL5GjKgn4", q:"Dinner in Motion Eindhoven",
      web:"http://www.dinnerinmotion.nl/", insta:null,
      img:null },

    { name:"VANE Restaurant & Skybar", area:"Vestdijk · Centrum", tier:4, cost:"€40–70 pp", vibe:"Rooftop",
      desc:"15th-floor rooftop with panoramic city-and-trees views and inventive cocktails. The restaurant below serves refined courses against the sunset. The spot for celebrating.",
      placeId:"ChIJ1Xjj2RzZxkcRKf5A0IFA_K8", q:"VANE Restaurant Eindhoven",
      web:"https://www.vane-eindhoven.nl/en/", insta:"https://www.instagram.com/vane_eindhoven/",
      img:null },

    { name:"Restaurant Kazerne", area:"Paradijslaan · Centrum", tier:4, cost:"€40–70 pp", vibe:"Design venue",
      desc:"Inside a former 1825 military barracks — restaurant, hotel and rotating art/design exhibition in one. Large open kitchen, dramatic custom lighting, chef's menus.",
      placeId:"ChIJMe6p8gPZxkcRerd8jOE-hGU", q:"Restaurant Kazerne Eindhoven",
      web:"https://kazerne.com/eat-drink/bar-bistro-kazerne/", insta:"https://www.instagram.com/kazerne_eindhoven/",
      img:null },

    { name:"Restaurant De Luytervelde", area:"Woensel-Noord", tier:4, cost:"€45–80 pp", vibe:"Hidden gem",
      desc:"A little gem hidden between houses just above Eindhoven, in a lovely building. Colourful, creative, beautifully-plated French-leaning courses and standout sauces. Reserve — it fills up.",
      placeId:"ChIJTxHixwHcxkcRV57XJwjdyZE", q:"Restaurant De Luytervelde Eindhoven",
      web:"http://deluytervelde.nl/", insta:null,
      img:null },

    { name:"Matsu Beef Atelier", area:"Strijp-S", tier:4, cost:"€60–90 pp", vibe:"Wagyu & wine",
      desc:"A beautiful beef atelier devoted to wagyu and fine wines. High-quality, beautifully-prepared tasting menus — aburi nigiri on crispy rice, tartare, premium cuts. A real occasion.",
      placeId:"ChIJIb7BFmvZxkcRw3bFlZac0xI", q:"Matsu Beef Atelier Eindhoven",
      web:"https://www.matsu.nl/", insta:"https://www.instagram.com/matsu.eindhoven/",
      img:null },
  ],

  activities: [
    { name:"Barkeet Arcade Bar", area:"Stratumseind · Centrum", tier:1, cost:"€5 + drinks", vibe:"Arcade bar",
      desc:"Pay €5 for a whole day of arcade machines, board and table games, plus a rooftop terrace over the river. Brilliant for a group or a low-key date.",
      placeId:"ChIJI4q667TZxkcRQKd-Slcft18", q:"Barkeet Eindhoven",
      web:"https://barkeet.nl/", insta:null,
      img:null },

    { name:"Op Noord — Outdoor Minigolf", area:"Eindhoven Noord", tier:1, cost:"€8–15 pp", vibe:"Minigolf",
      desc:"Well-kept outdoor minigolf with a café-bar attached. Friendly staff, sunny-afternoon energy — a proven team-building or first-date warm-up.",
      placeId:"ChIJ98B3vrLexkcRD1x0QfA6A8c", q:"Op Noord Eindhoven",
      web:"http://www.opnoord.nl/", insta:null,
      img:null },

    { name:"Glowgolf", area:"Vijfkamplaan", tier:1, cost:"€10–15 pp", vibe:"Glow minigolf",
      desc:"Glow-in-the-dark 3D minigolf with arcade and a bar — surprisingly great fun for grown-ups, statues and trippy black-light everywhere.",
      placeId:"ChIJCVu7f7HexkcROOq6B_oh22U", q:"Glowgolf Eindhoven",
      web:"http://www.hollywood.nl/eindhoven", insta:null,
      img:null },

    { name:"Peakz Padel (Beursgebouw)", area:"Centrum", tier:1, cost:"€10–20 pp", vibe:"Padel",
      desc:"Padel courts right in the centre with a bar to hang out afterwards. Easy to pick up, genuinely fun for a mixed-ability group.",
      placeId:"ChIJBVYE-ObZxkcRo2Bgp29N27A", q:"Peakz Padel Eindhoven Beursgebouw",
      web:"https://www.peakzpadel.nl/locaties/beursgebouw", insta:null,
      img:null },

    { name:"Laser Quest", area:"Oude Stadsgracht · Centrum", tier:1, cost:"€10–18 pp", vibe:"Laser tag",
      desc:"Laser tag in a big, twisty multi-level maze, plus pool tables and beer. Get a printed stats sheet at the end — great for competitive groups.",
      placeId:"ChIJHypxcgLZxkcRSwzljbFgFWs", q:"Laser Quest Eindhoven",
      web:"http://www.lqehv.nl/", insta:null,
      img:null },

    { name:"E.S.H. Da Vinci — Archery", area:"Amazonenlaan", tier:1, cost:"€15–25 pp", vibe:"Archery",
      desc:"Archery club with beginner courses, indoor and outdoor (up to 90 m). Members call it 'farmer meditation' — focus, friendly competition and a calm head.",
      placeId:"ChIJKwn5N9rYxkcRNEqD1UXnu1o", q:"ESH Da Vinci Eindhoven",
      web:"http://www.eshdavinci.nl/", insta:null,
      img:null },

    { name:"Rabauw Brewpub", area:"Strijp-S", tier:2, cost:"€15–30 pp", vibe:"Craft brewery",
      desc:"A small craft brewery with a great range of stouts and IPAs on tap, free pool and brilliant vibes. Do a tasting flight and settle in.",
      placeId:"ChIJFZwIIZjZxkcRc-H1X_-1pIY", q:"Rabauw Brewpub Eindhoven",
      web:"https://rabauw.org/", insta:null,
      img:null },

    { name:"Stadsbrouwerij — Beer Tasting", area:"Bleekweg · Centrum", tier:2, cost:"€15–30 pp", vibe:"Brewery",
      desc:"City brewery with flights of house beers and food — a relaxed, sociable base for the start of an evening with friends or colleagues.",
      placeId:"ChIJTdEwlv3YxkcR-QZQLGAgFk8", q:"Stadsbrouwerij Eindhoven",
      web:"https://stadsbrouwerijeindhoven.nl/", insta:"https://www.instagram.com/stadsbrouwerijeindhoven/",
      img:null },

    { name:"Paint Spat — Neon Paint Fight", area:"Kronehoefstraat", tier:2, cost:"€25–40 pp", vibe:"Glow painting",
      desc:"A glow-in-the-dark neon paint-fight room (rated 4.9) — chaotic, creative, hilarious. You take your canvases home. Totally different from the usual night out.",
      placeId:"ChIJqwrc5d7ZxkcRa2TdfJzSvvQ", q:"Paint Spat Eindhoven",
      web:"https://paintspat.nl/", insta:null,
      img:null },

    { name:"Rembrandt van Wine — Sip & Paint", area:"Klokgebouw · Strijp-S", tier:2, cost:"€30–45 pp", vibe:"Paint & wine",
      desc:"Sip & paint with an open wine bar (rated 4.7): music, colour and unlimited wine while you make a canvas you're weirdly proud of. Ideal first date or cosy group night.",
      placeId:"ChIJkz7QTwLZxkcRmy2uSIygBc0", q:"Rembrandt van Wine Eindhoven",
      web:"https://www.rembrandtvanwine.nl/sip-and-paint-eindhoven/", insta:null,
      img:null },

    { name:"Hezemans Indoor Karting", area:"Vijfkamplaan", tier:2, cost:"€20–35 pp", vibe:"Karting",
      desc:"Indoor electric go-karting plus an axe-throwing bar and arcade under one roof — the classic adrenaline group outing with drinks to follow.",
      placeId:"ChIJm98of7TexkcR8mvHswMPxno", q:"Hezemans Indoor Karting Eindhoven",
      web:"http://www.hezemans.nl/", insta:null,
      img:null },

    { name:"Another World VR Arena", area:"Rechtestraat · Centrum", tier:2, cost:"€20–35 pp", vibe:"VR",
      desc:"Open free-roam VR arena where you can play co-op games and grab a beer right beside the action. Easy, social, central.",
      placeId:"ChIJJ8O3JwvZxkcR1gj4Bn8-6nk", q:"Another World VR Arena Eindhoven",
      web:"https://eindhoven.another-world.com/", insta:null,
      img:null },

    { name:"Klimrijk Brabant — Tree Climbing", area:"Veldhoven", tier:2, cost:"€20–30 pp", vibe:"Forest adventure",
      desc:"A high-ropes adventure park in the forest: courses through the treetops, plus ATVs and e-bikes. Fresh air and real adrenaline, great for a daytime team day.",
      placeId:"ChIJ74UMmoTQxkcRCYQ8ZnqMUgc", q:"Klimrijk Brabant Veldhoven",
      web:"https://www.klimrijk.nl/", insta:null,
      img:null },

    { name:"Clay Atelier — Pottery Painting", area:"Hoogstraat · Centrum", tier:2, cost:"€25–40 pp", vibe:"Ceramics",
      desc:"Relaxed ceramic-painting workshop (rated 4.9) with a drink and a pastry — clear guidance, lovely shop, two-week pickup of your finished piece. A great date.",
      placeId:"ChIJwVE6KAnZxkcR9XSsKC44pBc", q:"Clay Atelier Eindhoven",
      web:"https://www.clayateliereindhoven.nl/", insta:null,
      img:null },

    { name:"Seven and Half Ceramic", area:"Lijsterbesstraat", tier:3, cost:"€30–45 pp", vibe:"Ceramics studio",
      desc:"Intimate wheel-throwing and ceramics workshops (rated 5.0) with patient, skilled hosts. A calm, hands-on afternoon that turns into a proper hobby for some.",
      placeId:"ChIJf_dE2wjZxkcRrVeVBU9JTBs", q:"Seven and Half Ceramic Eindhoven",
      web:"https://seven-and-half-ceramic.com/", insta:null,
      img:null },

    { name:"The Revellers — Cocktail Workshop", area:"Stratumseind · Centrum", tier:3, cost:"€15–40 pp", vibe:"Mixology",
      desc:"A 5.0-rated cocktail bar run by two mixology nerds — bespoke drinks built around your taste, plus hands-on workshops. Perfect for a group or a date.",
      placeId:"ChIJFwFHemHZxkcRcMpFuWPuTRQ", q:"The Revellers Eindhoven",
      web:"http://therevellers.bar/", insta:null,
      img:null },

    { name:"Twist — Cocktails & Tapas", area:"Scheldestraat", tier:3, cost:"€25–45 pp", vibe:"Cocktails",
      desc:"A cocktail-and-tapas spot with a big wall of spirits, a creative chef from Alicante and the option to do a workshop. A hidden gem between the centre and the stadium.",
      placeId:"ChIJm_G0GifZxkcR4ExenHFOO7c", q:"Twist Hospitality Eindhoven",
      web:"https://www.twist-hospitality.nl/", insta:null,
      img:null },

    { name:"WRKSHOP — Team Activities", area:"Willem de Zwijgerstraat", tier:3, cost:"€25–45 pp", vibe:"Team building",
      desc:"Turn-key group experiences: pop-art workshops, karaoke, pub games and beer quizzes with hosts who keep the energy up. Built for team days.",
      placeId:"ChIJQ75K0QXZxkcRccLSWQBAXzc", q:"WRKSHOP Eindhoven",
      web:"https://wrkshop.nl/", insta:null,
      img:null },

    { name:"Enversed VR Experience", area:"Prof. Dr. Dorgelolaan", tier:3, cost:"€25–40 pp", vibe:"VR",
      desc:"A premium VR arena with co-op shooters, virtual museums and escape-style missions — well-run for groups, with snacks and drinks brought to your booth.",
      placeId:"ChIJ71qRvWvZxkcRu7PNs3Twe4M", q:"Enversed Eindhoven",
      web:"http://www.enversed.com/", insta:null,
      img:null },

    { name:"THE RAGE — Smash Room", area:"Eindhoven Noord", tier:3, cost:"€25–45 pp", vibe:"Rage room",
      desc:"A 5.0-rated rage room: smash everything in sight with a baseball bat to your own playlist. Safe, well-run and a genuinely cathartic group laugh.",
      placeId:"ChIJQ6dwwUnfxkcRZBLcRljJjy0", q:"THE RAGE Smash Rooms Eindhoven",
      web:"https://therage.nl/", insta:null,
      img:null },
  ],

  trips: [
    { name:"Biesbosch Boat Day", area:"Drimmelen · ~60 min · Rafał drives", tier:2, cost:"~€33 pp + dinner", vibe:"The big one 🛥️", feat:true,
      desc:"A full day on the water: a private 7-person sloep (no licence needed) through the UNESCO Biesbosch — narrow creeks, beavers, herons, open water — a BBQ lunch you can only reach by boat, an afternoon swim, and a waterfront dinner at sunset. Rafał drives door-to-door. This is the one everyone remembers.",
      placeId:"ChIJ70X4o1WcxkcRi42lHL80N5k", q:"Jachthaven Biesbosch Drimmelen",
      web:"https://watersport-botenverhuur.nl/", insta:null,
      plan:[
        {t:"08:30", h:"Pickup — Eindhoven", d:"Rafał collects everyone from home. No one arranges travel."},
        {t:"09:30", h:"Arrive Drimmelen", d:"Jachthaven Biesbosch. Park, check in, quick boat briefing — no licence needed."},
        {t:"10:00", h:"Cast off into the Biesbosch", d:"You take the helm. UNESCO national park: creeks, beavers, herons, open water."},
        {t:"12:00", h:"🔥 BBQ lunch (boat-only spot)", d:"Sail to In Plané Explorer or De Vischplaat island — BBQ with a pro chef + wine. Bar & toilet on board."},
        {t:"14:00", h:"Afternoon cruise", d:"Open water, swim if warm, find a sandy bank, music on. The park is huge — stay curious."},
        {t:"17:30", h:"Back to marina & freshen up", d:"Hand back the boat, short walk, get ready for dinner next door."},
        {t:"18:00", h:"Dinner at More-Itz", d:"4-course menu on the waterfront terrace, sunset over the water. (Het Panorama = cheaper option.)"},
        {t:"21:00", h:"Drop-off — Eindhoven", d:"Door-to-door delivery back home. 🎁 transport on Rafał."}
      ],
      planmeta:"Veldhoven/Eindhoven → Drimmelen ≈ 65 km via A27 · 7-person sloep ~€200/day · dinner More-Itz €57+ pp · best June–September",
      img:null },

    { name:"Loonse en Drunense Duinen", area:"Drunen · ~40 min drive", tier:1, cost:"Free · ~€5 parking", vibe:"Nature day",
      desc:"The closest thing the Netherlands has to a desert — drifting sand dunes, pine forest and heath. Borrow the free bikes, picnic on the dunes, finish at a forest café. A pocket adventure 40 minutes from home.",
      placeId:"ChIJW76EGzG-xkcRdPJq1UCR7CY", q:"Loonse en Drunense Duinen",
      web:"https://www.natuurmonumenten.nl/natuurgebieden/nationaal-park-loonse-en-drunense-duinen", insta:null,
      img:null },

    { name:"Den Bosch — Canals & Cathedral", area:"'s-Hertogenbosch · ~30 min train", tier:2, cost:"€15–30 + travel", vibe:"Historic city",
      desc:"Hop the train to the Netherlands' finest Gothic cathedral, then cruise the hidden Binnendieze canals beneath the old town and devour a Bossche Bol (giant chocolate cream puff). Easy, classic, close.",
      placeId:"ChIJB55Bu_fuxkcR0yjSfy05V78", q:"Sint-Jan Cathedral Den Bosch",
      web:"https://www.sint-jan.nl/", insta:"https://www.instagram.com/bezoekdenbosch/",
      img:null },

    { name:"Utrecht — Canals & Dom Tower", area:"Utrecht · ~1 h train", tier:2, cost:"Travel + city", vibe:"Canal city",
      desc:"The Netherlands' tallest church tower over a city of two-level wharf canals, with terraces right at the water. Climb the Dom, drift the canals, café-hop. A prettier, calmer Amsterdam.",
      placeId:"ChIJgf7hSkVvxkcRNQQW-7nl0T8", q:"Dom Tower Utrecht",
      web:"https://www.domtoren.nl/", insta:"https://www.instagram.com/visit.utrecht/",
      img:null },

    { name:"Rotterdam — Markthal & Cube Houses", area:"Rotterdam · ~1 h 15 train", tier:2, cost:"Travel + city", vibe:"Architecture",
      desc:"The Netherlands at its most futuristic: graze the vaulted Markthal food hall, gawp at the tilted Cube Houses, then walk the river and the port skyline. A design-lover's day out.",
      placeId:"ChIJexHTc1wzxEcRGPuXpxt5bkM", q:"Markthal Rotterdam",
      web:"https://www.markthal.nl/en/", insta:"https://www.instagram.com/rotterdammakeithappen/",
      img:null },

    { name:"Maastricht — Old Town", area:"Maastricht · ~1 h 15 train", tier:3, cost:"Travel + city", vibe:"Burgundian city",
      desc:"The oldest, most Burgundian city in the country: grand squares, a bookshop inside a medieval church, riverside terraces and great food. A proper romantic day trip south.",
      placeId:"ChIJUYk7-43pwEcR6zckiME_EKA", q:"Vrijthof Maastricht",
      web:"https://vrijthofmaastricht.nl/", insta:"https://www.instagram.com/visitmaastricht/",
      img:null },

    { name:"Efteling Theme Park", area:"Kaatsheuvel · ~45 min drive", tier:3, cost:"~€44 ticket", vibe:"Theme park",
      desc:"One of Europe's oldest and most beautiful theme parks — fairytale forest, world-class coasters, obsessive detail everywhere. A full, joyful day of being a kid again.",
      placeId:"ChIJB0P0r6mWxkcRmrhc7bHaO0Q", q:"Efteling Kaatsheuvel",
      web:"https://www.efteling.com/", insta:"https://www.instagram.com/efteling/",
      img:null },

    { name:"Antwerp — Grote Markt", area:"Belgium · ~1 h 15 drive", tier:3, cost:"Travel + city", vibe:"City break",
      desc:"Cross into Belgium for a magnificent old square, a soaring cathedral, the diamond and fashion quarters — and frites, waffles and proper Belgian beer. A different country before dinner.",
      placeId:"ChIJY6eTP_b2w0cRnvPtAhhlczY", q:"Grote Markt Antwerp Belgium",
      web:"https://www.visitantwerpen.be/en", insta:"https://www.instagram.com/visit_antwerpen/",
      img:null },

    { name:"Kröller-Müller & Hoge Veluwe", area:"Otterlo · ~1 h 15 drive", tier:3, cost:"~€40 park + museum", vibe:"Art & nature",
      desc:"Europe's largest sculpture garden and a huge Van Gogh collection, set inside a national park you cross on free white bikes. Art, forest and heath in one unforgettable day.",
      placeId:"ChIJ59IECAaxx0cRXiACiCogHF8", q:"Kroller-Muller Museum Otterlo",
      web:"https://krollermuller.nl/", insta:"https://www.instagram.com/krollermuller/",
      img:null },

    { name:"Cologne — Cathedral & Old Town", area:"Germany · ~2 h drive", tier:4, cost:"Travel + city", vibe:"City break",
      desc:"The big one: a monumental Gothic cathedral that towers over the Rhine, a riverside old town and traditional brewhouses pouring Kölsch. A full-day border-crossing adventure.",
      placeId:"ChIJLz2cNqUlv0cRxqnjljiR7Ck", q:"Cologne Cathedral Germany",
      web:"https://www.koelner-dom.de/", insta:"https://www.instagram.com/koeln/", img:null },

    { name:"Bruges — Medieval Fairytale", area:"Belgium · ~1 h 45 drive", tier:3, cost:"Travel + city", vibe:"Bucket list",
      desc:"One of Europe's best-preserved medieval cities: canals, cobbles, belfry, chocolate and beer everywhere. Climb the tower, take a boat through the canals, eat your weight in waffles. Postcard-perfect.",
      placeId:"ChIJ5Q4l1mZuwUcRkr8gp_2QXZk", q:"Markt Bruges Belgium",
      web:"https://www.visitbruges.be/en", insta:"https://www.instagram.com/visitbruges/", img:null },

    { name:"Giethoorn — 'Venice of the North'", area:"Overijssel · ~1 h 45 drive", tier:3, cost:"Travel + boat", vibe:"Bucket list",
      desc:"A village with (almost) no roads — just canals, footbridges and thatched farmhouses. Rent a whisper-boat and drift through one of the most peaceful, photogenic places in the country. Pure escapism.",
      placeId:"ChIJWxLM6chUyEcR4Tk0_jUGAQM", q:"Giethoorn Netherlands",
      web:"https://www.giethoorn.com/", insta:"https://www.instagram.com/visitgiethoorn/", img:null },
  ],

  summer: [
    { name:"Corso Zundert", area:"Zundert · ~35 min drive", tier:1, cost:"~€13 entry", vibe:"Sep 6–7, 2026", date:"6–7 September 2026",
      desc:"The largest flower parade ON EARTH — and it's basically next door. Twenty hamlets spend a year building 9-metre, 19-metre-long floats covered in millions of locally-grown dahlias, then parade them through town. UNESCO-listed, 80+ years old, unforgettable.",
      placeId:"ChIJ7yY8mC0FxkcRRTJzBhq0pPg", q:"Bloemencorso Zundert",
      web:"https://corsozundert.nl/en/", insta:"https://www.instagram.com/corsozundert/", img:null },

    { name:"WiSH Outdoor", area:"Lieshout · ~15 min drive", tier:3, cost:"Festival ticket", vibe:"Summer 2026", date:"Summer 2026",
      desc:"A massive three-day crossover festival — hardstyle, house and Dutch pop with jaw-dropping stage design — right on your doorstep. For 2026 it moves to the Bavaria Brewery grounds in Lieshout with a new 'Showtime' theme. As local as a world-class festival gets.",
      placeId:null, q:"WiSH Outdoor Lieshout", web:"https://www.wishoutdoor.com/", insta:"https://www.instagram.com/wishoutdoor/", img:null },

    { name:"Down the Rabbit Hole", area:"Beuningen · ~1 h drive", tier:4, cost:"€100+ / 3-day", vibe:"Jul 3–5, 2026", date:"3–5 July 2026",
      desc:"The coolest indie/electronic festival in the country — psychedelic lakeside site, circus-tent stages, swimming between sets. 2026 lineup includes Florence + The Machine, Little Simz and The xx. Camp or glamp at the 'Rabbit Resort'.",
      placeId:null, q:"Down the Rabbit Hole festival Beuningen", web:"https://downtherabbithole.nl/", insta:"https://www.instagram.com/dtrhfestival/", img:null },

    { name:"Awakenings Festival", area:"Hilvarenbeek · ~30 min drive", tier:4, cost:"Festival ticket", vibe:"Summer 2026", date:"Summer 2026",
      desc:"The world's biggest name in techno, outdoors at Beekse Bergen — Charlotte de Witte, Amelie Lens, Adam Beyer, Joris Voorn and more across colossal stages. A pilgrimage for anyone who loves electronic music, half an hour away.",
      placeId:null, q:"Beekse Bergen Hilvarenbeek", web:"https://www.awakenings.com/", insta:"https://www.instagram.com/awakenings/", img:null },

    { name:"Bloemencorso Bollenstreek", area:"Noordwijk → Haarlem · ~1 h 45", tier:1, cost:"Free (grandstand €20–50)", vibe:"Apr 18, 2026", date:"18 April 2026",
      desc:"The famous spring flower parade: 42 km of giant floats built from millions of tulips and hyacinths, rolling past Keukenhof from Noordwijk to Haarlem. Combine it with the tulip fields in full bloom for the most Dutch day imaginable.",
      placeId:null, q:"Keukenhof Lisse", web:"https://bollenstreek.nl/bloemencorso-flower-parade-bollenstreek/?lang=en", insta:"https://www.instagram.com/bloemencorsobollenstreek/", img:null },

    { name:"Carnival in Brabant", area:"Den Bosch / Eindhoven · local", tier:1, cost:"Free", vibe:"Feb 2027", date:"February 2027",
      desc:"For three days the whole south goes gloriously mad: costumes, brass bands, parades and packed bars. Den Bosch becomes 'Oeteldonk' and Eindhoven 'Lampegat'. The most uniquely Brabant thing there is — worth planning ahead for.",
      placeId:"ChIJ_____zHvxkcR0NQ2zU6V6QI", q:"Oeteldonk Den Bosch carnival", web:"https://www.visitbrabant.com/en", insta:null, img:null },
  ]
};
